# Generated by Django 3.2 on 2021-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailrecipient',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
